[package]
name = "gtk-file-to-player"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.0", package = "gtk4", features = ["v4_18"] }
serde = { version = "1.0", features = ["derive"] }
sqlite = "0.37.0"
toml = "0.8"
