// rename this file to config.toml and fill in the values

database_path = "/path/to/database"
song_directory = "/path/to/songs"

window_title = "My Video Player"
search_placeholder = "Search for videos"
